apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: store-restserver
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/fabric-restserver
    git: https://github.com/omerabbas01/blockchain-automation-framework.git
    ref: develop
  releaseName: store-restserver
  values:
    metadata:
      namespace: store-net
    server:
      name: store-restserver
      port: 20001
      localmspid: storeMSP
      image: hub.docker.com/u/axiscyber/supplychain_fabric:rest_server_latest
      username: user1
      cert_path: "/secret/tls/user1.cert"
      key_path: "/secret/tls/user1.pem"
    storage:
      storageclassname: storesc
      storagesize: 512Mi
    vault:
      address: localhost:8200
      role: vault-role
      authpath: devstore-net-auth
      secretprefix: secret/crypto/peerOrganizations/store-net
      serviceaccountname: vault-auth
      imagesecretname: regcred
      image: hyperledgerlabs/alpine-utils:1.0
    service:
      servicetype: ClusterIP
      ports:
        apiPort: 20001
        targetPort: 8000
    connection:
      peer: peer0.store-net
      peerAddress: peer0.store-net
      peerPort: 7051
      ordererAddress: orderer1.org1ambassador.blockchaincloudpoc.com
      ordererPort: 8443