apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-expressapi
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/expressapp
    git: "https://github.com/omerabbas01/blockchain-automation-framework.git"
    ref: "develop"
  releaseName: manufacturerfabric-expressapi
  values:
    nodeName: manufacturer-expressapi
    metadata:
      namespace: manufacturer-net
    replicaCount: 1
    expressapp:
      serviceType: ClusterIP
      image: hub.docker.com/u/axiscyber/supplychain_fabric:express_app_latest
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        apiUrl: http://manufacturer-restserver.manufacturer-net:20001/api/v1
    proxy:
      provider: haproxy
      name: manufacturer
      type: fabric
      external_url_suffix: org2ambassador.blockchaincloudpoc.com
      peer_name: peer0
